commit:
  templates:
    bug:
      description: Fix that resolves an unintended issue
      content: |
        {ticket_num} 🐛 {message}
    break:
      description: Breaking change that could break a consuming application
      content: |
        {ticket_num} ⚠️ {message}

    deps:
      description: Dependency update or migration to a new dependency
      content: |
        {ticket_num} 📦 {message}

    docs:
      description: Documentation change
      content: |
        {ticket_num} 📖 {message}

    feature:
      description: Adds new functionality
      content: |
        {ticket_num} ✨ {message}

    refactor:
      description: Improvement of code / structure without adding new functionality
      content: |
        {ticket_num} 🧹 {message}

    test:
      description: Adds or improves the existing tests related to the code base
      content: |
        {ticket_num} 🧪 {message}