on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: Release and publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build

  publish-dry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run

  publish:
    runs-on: ubuntu-latest
    env:
      CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          # Allows us to use the git tag version as the package version
          command: install
          args: cargo-release
      - name: Update Cargo.toml version
        run: |
          TAG_VERSION=$(echo $GITHUB_REF | cut -d '/' -f 3)
          cargo release version "$TAG_VERSION" --no-confirm --execute
      # Publish and allow dirty since the Cargo.toml version is changed.
      - name: Publish package
        run: cargo publish --token "$CARGO_TOKEN" --allow-dirty
    needs: [build, publish-dry]
